// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RegionalServerClient is the client API for RegionalServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegionalServerClient interface {
	ReceiveValue(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Response, error)
}

type regionalServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegionalServerClient(cc grpc.ClientConnInterface) RegionalServerClient {
	return &regionalServerClient{cc}
}

func (c *regionalServerClient) ReceiveValue(ctx context.Context, in *Value, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/regional.RegionalServer/ReceiveValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegionalServerServer is the server API for RegionalServer service.
// All implementations must embed UnimplementedRegionalServerServer
// for forward compatibility
type RegionalServerServer interface {
	ReceiveValue(context.Context, *Value) (*Response, error)
	mustEmbedUnimplementedRegionalServerServer()
}

// UnimplementedRegionalServerServer must be embedded to have forward compatible implementations.
type UnimplementedRegionalServerServer struct {
}

func (UnimplementedRegionalServerServer) ReceiveValue(context.Context, *Value) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveValue not implemented")
}
func (UnimplementedRegionalServerServer) mustEmbedUnimplementedRegionalServerServer() {}

// UnsafeRegionalServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegionalServerServer will
// result in compilation errors.
type UnsafeRegionalServerServer interface {
	mustEmbedUnimplementedRegionalServerServer()
}

func RegisterRegionalServerServer(s grpc.ServiceRegistrar, srv RegionalServerServer) {
	s.RegisterService(&RegionalServer_ServiceDesc, srv)
}

func _RegionalServer_ReceiveValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegionalServerServer).ReceiveValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regional.RegionalServer/ReceiveValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegionalServerServer).ReceiveValue(ctx, req.(*Value))
	}
	return interceptor(ctx, in, info, handler)
}

// RegionalServer_ServiceDesc is the grpc.ServiceDesc for RegionalServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegionalServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "regional.RegionalServer",
	HandlerType: (*RegionalServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveValue",
			Handler:    _RegionalServer_ReceiveValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
