# Usamos una imagen base de Golang 1.21.1
FROM golang:1.21.1

# Establecemos el directorio de trabajo en /app
WORKDIR /app

# Copiamos los archivos go.mod y go.sum a la imagen
COPY go.mod .
COPY go.sum .

# Copiamos todo el contenido de la carpeta ../Central a /app en la imagen
COPY ../Central /app


# Exponemos el puerto en el que se ejecutará el servidor
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["./Central"]
